build:
  version: "1.0"

accounts:
  message: "Welcome to Quyet Eazybank accounts prod APIs"
  contactDetails:
    name: "Quyet Tran Vu Prod"
    email: "quyettranvuprod@gmail.com"
  onCallSupport:
      -(555) 738 5612
      -(555) 748 5712